In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [8]:
X = np.array([[1], [1], [0], [0]])
y = np.array([1, 1, 0, 0])

# Guassian

In [60]:
model = GaussianNB()
results = model.fit(X, y)
results.predict(X)
print  'y: ', y,'\nX:\n', X, '\npredict: ', results.predict(X), '\nproba: \n', results.predict_proba(X)

y:  [1 1 1 1] 
X:
[[1]
 [1]
 [1]
 [1]] 
predict:  [1 1 1 1] 
proba: 
[[ nan]
 [ nan]
 [ nan]
 [ nan]]


# Do the same thing with bernoulli and multinomial

In [61]:
X = np.array([[1], [1], [0], [0]])
y = np.array([1, 1, 0, 0])
model = BernoulliNB()
results = model.fit(X, y)
results.predict(X)
print  'y: ', y,'\nX:\n', X, '\npredict: ', results.predict(X), '\nproba: \n', results.predict_proba(X)

y:  [1 1 0 0] 
X:
[[1]
 [1]
 [0]
 [0]] 
predict:  [1 1 0 0] 
proba: 
[[ 0.25  0.75]
 [ 0.25  0.75]
 [ 0.75  0.25]
 [ 0.75  0.25]]


# Do the same but with Multinomial

In [58]:
model = MultinomialNB()
results = model.fit(X, y)
results.predict(X)
print  'y: ', y,'\nX:\n', X, '\npredict: ', results.predict(X), '\nproba: \n', results.predict_proba(X)

y:  [1 1 1 1] 
X:
[[1]
 [1]
 [1]
 [1]] 
predict:  [1 1 1 1] 
proba: 
[[ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]
